economicwebsite/accounts/urls.py
from django.urls import path, re_path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('profile/<slug:slug>/', views.Profile.as_view(), name='profile'),
    path('my_trips/', views.TripList.as_view(), name='my_trips'),
    path('create_trip/', views.ChooseTripTypeView.as_view(), name='create_trip'),
    path('non_international/', views.TripView.as_view(), name='non_international'),
    path('international/', views.InternationalTripView.as_view(), name='international'),
    re_path(r'^delete_trip/(?P<pk>[0-9]+)$', views.TripDelete.as_view(), name='delete_trip'),
    re_path(r'^delete_inttrip/(?P<pk>[0-9]+)$', views.InternationalTripDelete.as_view(), name='delete_inttrip'),
]

economicwebsite/economicwebsite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from . import views
from . import settings

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('thanks/', views.ThanksView.as_view(), name='thanks'),
    path('trip_created/', views.TripCreated.as_view(), name='trip_created'),
    path('admin/', admin.site.urls),
    path('account/', include('accounts.urls'), name=None),
    path('accounts/', include('django.contrib.auth.urls')),
    path('avatar/', include('avatar.urls')),
    path('lazy_tags/', include('lazy_tags.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

economicwebsite/templates/base.html
<!DOCTYPE html>
{% load static %}
{% load bootstrap3 %}
{% load avatar_tags %}

<html>
<head>
    <title>{% block page_title %}{% endblock page_title %}</title>

    <!--Bootstrap CSS-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <!--Bootstrap jQuery-->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>

    <!--Bootstrap JS-->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

    <!-- STATIC FILES -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/master.css' %}">
    <script type="text/javascript" src="{% static 'js/master_js.js' %}"></script>

    <!-- Icon library -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <!-- Small text font -->
    <link href="https://fonts.googleapis.com/css?family=Titillium+Web" rel="stylesheet">

    <!-- The font of the "T" of the Logo of the website -->
    <link href="https://fonts.googleapis.com/css?family=Monoton" rel="stylesheet">  

    <!-- jQuery -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>


</head>
<body>

    <header>
        <!-- responsive nav bar -->
        <div class="nav-bar">
            <a href=""><i class="fa fa-bars"></i><span class="info"><img class="site-logo-small" src="{% static 'trip_images/logo.png' %}"></span></a>
        </div>
        
        <!-- navigation -->
        <nav>
            <ul>
                {% if user.is_authenticated %}
                    <div><a href="{% url 'accounts:profile' user.username %}">{% avatar user 50 class="img-circle img-responsive focus pic" %}</a></div>
                {% endif %}
                <div><a href="{% url 'home' %}"><img class="site-logo" src="{% static 'trip_images/logo.png' %}"></a></div>
                <li {% if request.path == '/' %} class="active" {% endif %} ><a href="{% url 'home' %}"><i class="fa fa-home"></i> <strong>HOME</strong></a></li>
                {% if user.is_authenticated %}
                    <li {% if "/account/create_trip/" in request.path %} class="active"{% endif %} ><a href="{% url 'accounts:create_trip' %}"><i class="fa fa-car"></i> <strong>CREATE A TRIP</strong></a></li>
                    <li {% if "/account/my_trips/" in request.path %} class="active"{% endif %} ><a href="{% url 'accounts:my_trips' %}"><i class="fa fa-list-alt"></i> <strong>MY TRIPS</strong></a></li>
                    <!-- <li {% if "/account/profile/" in request.path %} class="active"{% endif %} ><a href="{% url 'accounts:profile' user.username %}"><i class="fa fa-user"></i>  <strong>{{ user.username|upper }}</strong></a></li> -->
                    <li><a href="{% url 'accounts:logout' %}"><i class="fa fa-sign-out"></i> <strong>LOGOUT</strong></a></li>
                {% else %}
                    <li {% if request.path == "/account/login/" %} class="active"{% endif %} ><a href="{% url 'accounts:login' %}"><i class="fa fa-arrow-right"></i> <strong>LOGIN</strong></a></li>
                    <li {% if request.path == "/account/signup/" %} class="active last"{% endif %} class="last"><a href="{% url 'accounts:signup' %}"><i class="fa fa-pencil"></i> <strong>SIGN UP</strong></a></li>
                {% endif %}
            </ul>
        </nav> <!-- navigation end -->
        
    </header> <!-- header end -->

    <!-- <hr class="menu"> -->

    <!-- CONTENT -->
    <div class='jumbotron jumbotron-fluid'>
        <div class='container-fluid'>
            {% block content %}
                
            {% endblock content %}
        </div>
    </div>
    

</body>
</html>

economicwebsite/templates/home.html
{% extends "base.html" %}

{% block page_title %}Home{% endblock page_title %}

{% block content %}

	<h4 class='display-4 page_header' align='center'>Welcome to <span class="letter-t">T</span>rippy</h4>
	<div align="center">
		<p class="lead">This is a website that calculates the price of your <strong>car</strong> trips.</p>
		
		<hr width="50%">
		<p class="lead">So how to create a trip?</p>
		<div class="info">

			<p>Firstly, you'll have to <strong>SIGN UP</strong> and <strong>LOG IN</strong>. After that, 	open the <strong>CREATE A TRIP</strong> tab.</p>
			<p>Then, you'll have to choose whether you want to travel <strong>locally</strong> or <strong>internationally</strong>.</p>
			<br>
			<p><strong>This is how you have to enter the information for your trip results to be valid:</strong></p>
			<div class="infotext info">
				<ul>
					<li>Countries (in English)</li>
					<li>Towns or villages (in English)</li>
					<li>Fuel cost (in Euro)</li>
					<li>Fuel consumption (Litres per 100km, <strong>enter only the litres</strong>)</li>
				</ul>
			</div>
		
		<hr width="50%">
		</div>
		<p class="lead">Finally, you'll have a <strong>personal</strong> list of trips in your <strong>MY TRIPS</strong> tab!</p>

	</div>

{% endblock content %}

economicwebsite/templates/thanks.html
{% extends "base.html" %}
{% block content %}

	<h1 class='display-4' align='center'>Thank you for registering!</h1>
	
{% endblock content %}

economicwebsite/templates/trip_created.html
{% extends "base.html" %}

{% block content %}
	<div align="center">
		<h1 class="display-4">Your trip statistic has been created!</h1>
		<h1 class="display-4">You can go and check it out on your 'MY TRIPS' page!</h1>
	</div>

	
{% endblock content %}