economicwebsite/accounts/urls.py
from django.urls import path, re_path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('profile/<slug:slug>/', views.Profile.as_view(), name='profile'),
    path('my_trips/', views.TripList.as_view(), name='my_trips'),
    path('create_trip/', views.ChooseTripTypeView.as_view(), name='create_trip'),
    path('non_international/', views.TripView.as_view(), name='non_international'),
    path('international/', views.InternationalTripView.as_view(), name='international'),
    re_path(r'^delete_trip/(?P<pk>[0-9]+)$', views.TripDelete.as_view(), name='delete_trip'),
    re_path(r'^delete_inttrip/(?P<pk>[0-9]+)$', views.InternationalTripDelete.as_view(), name='delete_inttrip'),
]

economicwebsite/economicwebsite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from . import views
from . import settings

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('thanks/', views.ThanksView.as_view(), name='thanks'),
    path('trip_created/', views.TripCreated.as_view(), name='trip_created'),
    path('admin/', admin.site.urls),
    path('account/', include('accounts.urls'), name=None),
    path('accounts/', include('django.contrib.auth.urls')),
    path('avatar/', include('avatar.urls')),
    path('lazy_tags/', include('lazy_tags.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

economicwebsite/accounts/forms.py
from django import forms
from .models import User, Trip

from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

from django.core.validators import RegexValidator

# A validation for the username, because the default validation accepts all unicode characters.
alphanumeric = RegexValidator(r'^[0-9a-zA-Z_]*$', 'Only English alphabetic characters, underscores and/or numbers are allowed.')

class UserCreateForm(UserCreationForm):

    # Adding the validation to our username field.
    username = forms.CharField(min_length=5, validators=[alphanumeric])

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

    def __init__(self, *args, **kwargs):
        '''
        Removing help_text(s) that are being displayed by default
        in the UserCreationForm (for a better look).
        '''

        super().__init__(*args, **kwargs)
        
        self.fields['username'].help_text = None

        self.fields['password1'].help_text = None

        self.fields['password2'].help_text = None


# class TripCreateForm(forms.ModelForm):

#     class Meta:
#         model = Trip
#         fields = ('country', 'town_1', 'town_2', 'fuel_cost', 'fuel_consumption')

#     def __init__(self, *args, **kwargs):
#         super().__init__(*args, **kwargs)
        
#         self.fields['town_1'].label = "From"
#         self.fields['town_2'].label = "To"

economicwebsite/accounts/views.py
import requests

from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView, DetailView, ListView, DeleteView, TemplateView
from .models import User, Trip, InternationalTrip
from django.core.exceptions import ValidationError
from django.db import IntegrityError
from django.http import HttpResponseRedirect

from django.contrib.auth import authenticate, login

from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin


from braces.views import LoginRequiredMixin

from . import forms
from . import countries_info



# MapQuest API Key
key = "03cXzah4oYwdKkvyfkPeeatkbBn2z3LO"


class SignUp(CreateView):
    '''
    SignUp view that uses the UserCreateForm that I've created.
    Logging in after registration success.
    '''

    template_name = "accounts/signup.html"
    success_url = reverse_lazy("home")
    form_class = forms.UserCreateForm

    # Login the user after Signing up
    def form_valid(self, form):
        valid = super().form_valid(form)
        username, password = form.cleaned_data.get('username'), form.cleaned_data.get('password1')
        new_user = authenticate(username=username, password=password)
        login(self.request, new_user)
        return valid


class Profile(DetailView):

    model = User
    slug_field = "username"
    template_name = "accounts/profile.html"

    def get_object(self, *args, **kwargs):
        return self.request.user


class TripList(ListView):

    model = Trip
    context_object_name = "trips"
    template_name = "accounts/my_trips.html"
    # paginate_by = 3

    def get_queryset(self):
        return self.model.objects.filter(user=self.request.user)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['international_trips'] = InternationalTrip.objects.filter(user=self.request.user)
        return context



class ChooseTripTypeView(TemplateView):

    template_name = "accounts/create_trip.html"



class TripView(CreateView):

    model = Trip
    template_name = "accounts/non_international.html"
    fields = ['country', 'From', 'to', 'fuel_cost', 'fuel_consumption']
    success_url = reverse_lazy("accounts:my_trips")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["non_international"] = context["form"]

        return context


    def form_valid(self, form):
        super().form_valid(form)

        try:
            url = 'http://www.mapquestapi.com/directions/v2/optimizedroute?key=' + key + \
                  '&json={"locations":["' + self.object.From + ',' + countries_info.countries[form.instance.country.lower()] + \
                  '","' + self.object.to + ',' + countries_info.countries[form.instance.country.lower()] + '"]}'

            req = requests.get(url)

            json_obj = req.json()

            self.object.country = self.object.country.capitalize()
            self.object.From = self.object.From.capitalize()
            self.object.to = self.object.to.capitalize()


            form.instance.distance = int(json_obj['route']['distance']*1.609344)

            fuel_used = self.object.fuel_consumption*form.instance.distance
        
            form.instance.money = int(fuel_used*self.object.fuel_cost/100)
            form.instance.time = json_obj['route']['formattedTime']
            form.instance.user = self.request.user
            
        except (KeyError, IntegrityError):
            form.add_error('__all__', "One of the cities does not exist in our data set!")
            return super().form_invalid(form)
        else:
            try:
                return super().form_valid(form)
            except:
                form.add_error('__all__', "You already have this trip in your MY TRIPS tab!")
                return super().form_invalid(form)



class InternationalTripView(CreateView):

    model = InternationalTrip
    template_name = "accounts/international.html"
    fields = ['first_country', 'From', 'second_country', 'to', 'fuel_cost', 'fuel_consumption']
    success_url = reverse_lazy("accounts:my_trips")

    def get_context_data(self, **kwargs):

        context = super().get_context_data(**kwargs)
        context["international"] = context["form"]

        return context

    def form_valid(self, form):

        super().form_valid(form)

        try:
            url = 'http://www.mapquestapi.com/directions/v2/optimizedroute?key=' + key + \
                  '&json={"locations":["' + self.object.From + ',' + countries_info.countries[form.instance.first_country.lower()] + \
                  '","' + self.object.to + ',' + countries_info.countries[form.instance.second_country.lower()] + '"]}'

            req = requests.get(url)

            json_obj = req.json()

            # Checking whether the API statuscode signals an error.
            if json_obj['info']['statuscode'] == 402:
                form.add_error('__all__', "It is impossible to travel by a car from {} to {}".format(self.object.From.title(), self.object.to.title()))
                return super().form_invalid(form)

            self.object.first_country = self.object.first_country.capitalize()
            self.object.second_country = self.object.second_country.capitalize()
            self.object.From = self.object.From.capitalize()
            self.object.to = self.object.to.capitalize()

            form.instance.distance = int(json_obj['route']['distance']*1.609344)

            fuel_used = self.object.fuel_consumption*form.instance.distance
        
            form.instance.money = int(fuel_used*self.object.fuel_cost/100)
            form.instance.time = json_obj['route']['formattedTime']
            form.instance.user = self.request.user

            
        except (KeyError, IntegrityError):
            form.add_error('__all__', "One of the cities does not exist in our data set!")
            return super().form_invalid(form)
        else:
            try:
                return super().form_valid(form)
            except:
                form.add_error('__all__', "You already have this trip in your MY TRIPS tab!")
                return super().form_invalid(form)


class TripDelete(SuccessMessageMixin, DeleteView):

    model = Trip
    success_url = reverse_lazy('accounts:my_trips')
    success_message = 'Your trip has been deleted successfully!'

    def delete(self, request, *args, **kwargs):
        messages.warning(self.request, self.success_message)
        return super().delete(request, *args, **kwargs)

class InternationalTripDelete(SuccessMessageMixin, DeleteView):

    model = InternationalTrip
    success_url = reverse_lazy('accounts:my_trips')
    success_message = 'Your international trip has been deleted successfully!'

    def delete(self, request, *args, **kwargs):
        messages.warning(self.request, self.success_message)
        return super().delete(request, *args, **kwargs)

economicwebsite/accounts/templates/accounts/create_trip.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block content %}
	
	

	<section>
		<a href="{% url 'accounts:non_international' %}" class="altbtn">
			<span class="altbtn-content"><h4 class="display-4">Local</h4></span>
			<span class="icon"><i class="fa fa-car" aria-hidden="true"></i></span>
		<a href="{% url 'accounts:international' %}" class="altbtn">
			<span class="altbtn-content"><h4 class="display-4">International</h4></span>
			<span class="icon"><i class="fa fa-globe" aria-hidden="true"></i></span>
		</a>
	</section>

{% endblock content %}

economicwebsite/accounts/templates/accounts/international.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block content %}
	
	<h4 align="center" class="display-3">Create a trip</h4>
	<br>
	<div align="center"><small class="info">This form is not case sensitive.</small></div>
	<div align="center">
		<form action="" method="POST">
			{% csrf_token %}
			{% bootstrap_form international %}
			<button type="submit" class="btn btn-outline-primary btn-lg">Create</button>
		</form>
	</div>
	
{% endblock content %}

economicwebsite/accounts/templates/accounts/login.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block page_title %}Login{% endblock page_title %}

{% block content %}
	
	<div class='container'>
		<h1 class='display-3 page_header' align='center'>Login</h1>
		<br>
		<form method="POST">
			{% csrf_token %}
			<div align='center'>
				{% bootstrap_form form %}
			</div>		
			<div align='center'>
				<button type="submit" class="btn btn-outline-primary btn-lg">Login</button>
			</div>
		</form>
	</div>
	
{% endblock content %}

economicwebsite/accounts/templates/accounts/my_trips.html
{% extends "base.html" %}

{% load bootstrap3 %}
{% load static %}

{% block content %}

	<div align="center">

		{% if messages %}
			{% for message in messages %}
				<div class="alert alert-danger" role="alert">
		            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
		            <strong class="info">{{ message }}</strong>
				    {{ messages.pop.0 }}
		        </div>
			{% endfor %}
		{% endif %}

		<div class="accordion" id="accordionExample">
		  <div class="card">
		    <div class="card-header" id="headingOne">
		      <h2 class="mb-0">
		        <button class="btn btn-outline-primary" type="button" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
		          Local
		        </button>
		      </h2>
		    </div>

		    <div id="collapseOne" class="collapse" aria-labelledby="headingOne" data-parent="#accordionExample">
		      <div class="card-body">    
		        {% for trip in trips %}
					<br>
					<div class="triplate">
						<div class="pin1"></div>
						<br>
						<p class="triplate-content" id="triptext"><strong>Country:</strong> {{ trip.country|title }}</p>
						<p class="triplate-content" id="triptext"><strong>Trip:</strong> {{ trip.From|title }} - {{ trip.to|title }}</p>
						<p class="triplate-content" id="triptext"><strong>Costs:</strong> {{ trip.money }}€</p>
						<p class="triplate-content" id="triptext"><strong>Time:</strong> {% if trip.time|slice:"0:1" == "0" %}
							{{ trip.time|slice:"1:2" }}h {% else %} {{ trip.time|slice:":2" }}h {% endif %}  
						{{ trip.time|slice:"3:5" }}m </p>
						<p class="triplate-content" id="triptext"><strong>Distance:</strong> {{ trip.distance }}km</p>
						<br>
						<p class="triplate-content" id="triptext">{{ trip.date|date:"d | M | Y | g:iA" }}</p>
						<form action="{% url 'accounts:delete_trip' trip.id %}" method="POST">
							{% csrf_token %}
							<button class="delbtn"><i class="fa fa-close"></i></button>
						</form>
						<br>
					</div>
					<hr class="menu">
				{% empty %}
					<h3>Your list of local trips is empty!</h3>
					<h5>Go to the CREATE A TRIP tab if you feel locally adventurous!</h5>
				{% endfor %}

		      </div>
		    </div>
		  </div>
		  <div class="card">
		    <div class="card-header" id="headingTwo">
		      <h2 class="mb-0">
		        <button class="btn btn-outline-primary collapsed" type="button" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
		          International
		        </button>
		      </h2>
		    </div>
		    <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionExample">
		      <div class="card-body">
		        
		        {% for trip in international_trips %}
					<br>
					<div class="triplate">
						<div class="pin1"></div>
						<br>
						<p class="triplate-content" id="triptext"><strong>Countries:</strong> {{ trip.first_country|title }} - {{ trip.second_country|title }}</p>
						<p class="triplate-content" id="triptext"><strong>Trip:</strong> {{ trip.From|title }} - {{ trip.to|title }}</p>
						<p class="triplate-content" id="triptext"><strong>Costs:</strong> {{ trip.money }}€</p>
						<p class="triplate-content" id="triptext"><strong>Time:</strong> {% if trip.time|slice:"0:1" == "0" %}
							{{ trip.time|slice:"1:2" }}h 
							{% else %}
							{{ trip.time|slice:":2" }}h 
							{% endif %}  
						{{ trip.time|slice:"3:5" }}m </p>
						<p class="triplate-content" id="triptext"><strong>Distance:</strong> {{ trip.distance }}km</p>
						<br>
						<p class="triplate-content" id="triptext">{{ trip.date|date:"d | M | Y | g:iA" }}</p>

						<form action="{% url 'accounts:delete_inttrip' trip.id %}" method="POST">
							{% csrf_token %}
							<button class="delbtn"><i class="fa fa-close"></i></button>
						</form>
						<br>
					</div>
					<hr class="menu">
				{% empty %}
					<h3>Your list of international trips is empty!</h3>
					<h5>Go to the CREATE A TRIP tab if you feel internationally adventurous!</h5>
				{% endfor %}
		      </div>
		    </div>
		  </div>		

		 <!-- Pagination -->
		<!--{% if is_paginated %}
			<div class="pagination">
				<span class="page-links">
					<span class="page-current">
						<p class="info">{% if page_obj.has_previous %}<a class="btn btn-outline-dark" href="/account/my_trips?page={{ page_obj.previous_page_number }}"><<</a>{% endif %}
						 <strong>Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
							{% if page_obj.has_next %}</strong><a class="btn btn-outline-dark" href="/account/my_trips?page={{ page_obj.next_page_number }}">>></a>{% endif %}</p>
					</span>
				</span>
			</div>
		{% endif %}			 -->

	<!--<br>
	<div class="triplate">
		<div class="pin1"></div>
		<br>
		<p class="triplate-content" id="triptext"><strong>Countries</strong> {{ trip.first_country|title }} - {{ trip.second_country|title }}</p>
		<p class="triplate-content" id="triptext"><strong>Trip</strong>: {{ trip.From|title }} - {{ trip.to|title }}</p>
		<p class="triplate-content" id="triptext"><strong>Costs</strong>: {{ trip.money }}€</p>
		<p class="triplate-content" id="triptext"><strong>Time</strong>: {{ trip.time }}</p>
		<p class="triplate-content" id="triptext"><strong>Distance</strong>: {{ trip.distance }}km</p>
	</div>-->
	</div>

	
{% endblock content %}

economicwebsite/accounts/templates/accounts/non_international.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block content %}

	<h4 align="center" class="display-3">Create a trip</h4>
	<br>
	<div align="center"><small class="info">This form is not case sensitive.</small></div>
	<div align="center">
		<form action="" method="POST">
			{% csrf_token %}
			{% bootstrap_form non_international %}
			<button type="submit" class="btn btn-outline-primary btn-lg">Create</button>
			<div style="display:none" class="loading"><h1>Loading...</h1>
		</form>
	</div>	
	
{% endblock content %}

economicwebsite/accounts/templates/accounts/profile.html
{% extends "base.html" %}
{% load bootstrap3 %}
{% load avatar_tags %}

{% block page_title %}Profile{% endblock page_title %}

{% block content %}
	<hr class="menu">
	<div align='center'>{% avatar user 100 class="img-oval img-responsive" %}</div>
	<h1 class='display-4 page_header' align='center'>{{ user.username }}</h1>
	<p class='info' align='center'>Email: {{ user.email }}</p>
	<br>
	<div align='center'><a class="btn btn-outline-primary" href="{% url 'avatar_change' %}">Change avatar</a></div>
	<hr class="menu">

	<br>
	<div align="center">

	</div>

{% endblock content %}

economicwebsite/accounts/templates/accounts/signup.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block page_title %}Signup{% endblock page_title %}

{% block content %}
	
	<div class='container'>
		<h1 class='display-3 page_header' align='center'>Sign Up</h1>
		<br>
		<form method="POST">
			{% csrf_token %}
			<div align='center'>
				{% bootstrap_form form %}
			</div>	
			<div align='center'>
				<button type="submit" class="btn btn-outline-primary btn-lg">Sign Up</button>
			</div>
		</form>
	</div>
	
{% endblock content %}	